s*//g
s/_//g
s/NNAAMMEE/NAME/g
s/OOPPTTIIOONNSS/OPTIONS/g
s/SSEEEE AALLSSOO/SEE ALSO/g
s/TTEESSTTSS/TESTS/g
s/AACCTTIIOONNSS/ACTIONS/g
s/SSYYNNOOPPSSIISS/SYNOPSIS/g
s/DDEESSCCRRIIPPTTIIOONN/DESCRIPTION/g
s/SSTTAANNDDAARRDDSS/STANDARDS/g
s/OOPPEERRAATTOORRSS/OPERATORS/g
s/EEXXPPRREESSSSIIOONNSS/EXPRESSIONS/g
s/HHIISSTTOORRYY/HISTORY/g
s/NNOOTTIICCEE/NOTICE/g
s/BBUUGGSS/BUGS/g
s/VVEERRSSIIOONN/VERSION/g
